import localFont from "next/font/local";
import { Toaster } from "@/components/ui/sonner";
import "aos/dist/aos.css";
import "./globals.css";

const montserratRegular = localFont({
  src: "./fonts/Montserrat-Regular.woff2",
  variable: "--font-montserrat-regular",
  display: "swap",
});

const montserratMedium = localFont({
  src: "./fonts/Montserrat-Medium.woff2",
  variable: "--font-montserrat-medium",
  display: "swap",
});

const montserratSemibold = localFont({
  src: "./fonts/Montserrat-SemiBold.woff2",
  variable: "--font-montserrat-semibold",
  display: "swap",
});

const montserratExtraBold = localFont({
  src: "./fonts/Montserrat-ExtraBold.woff2",
  variable: "--font-montserrat-extrabold",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserratRegular.variable} ${montserratMedium.variable} ${montserratSemibold.variable} ${montserratExtraBold.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
